[tool.black]
target-version = ["py310"]
line-length = 100
skip-magic-trailing-comma = false

[tool.ruff]
target-version = "py310"
line-length = 100
indent-width = 4

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false

[tool.ruff.lint]
preview = true
select = [
    "F",  # pyflakes
    "E",  # pycodestyle
    "W",  # pycodestyle
    "I",  # isort
    "UP",  # pyupgrade
    "ANN",  # flake8-annotations
    "A",  # flake8-builtins
    # "COM",  # flake8-commas
    "C4",  # flake8-comprehensions
    "G",  # flake8-logging-format
    "Q",  # flake8-quotes
    "SLF",  # flake8-self
    "SIM",  # flake8-simplify
    "TCH",  # flake8-tidy-imports
    # "ARG",  # flake8-unused-arguments
    "FIX",  # flake8-fixme
    "PD",  # flake8-pandas
    "RUF",  # ruff-specific-rules
]
ignore = [
    "ANN002",  # missing-type-args
    "ANN003",  # missing-type-kwargs
    "ANN204",  # missing-return-type-special-method
    "ANN401",  # any-type
]

[tool.ruff.lint.flake8-annotations]
mypy-init-return = true
